services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_backend
    volumes:
      - ./backend:/var/www/html
    environment:
      DB_HOST: mysql
      DB_DATABASE: bookstoredb
      DB_USERNAME: root
      DB_PASSWORD: secret
    ports:
      - 3096:3096
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env.local

  mysql:
    image: mysql:9.1
    container_name: mysql_database
    environment:
      MYSQL_DATABASE: bookstoredb
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - /mysql_data:/var/lib/mysql
